### PR TITLE
Stripe KYC claims limit

### PR DESCRIPTION
**Pull request by arik-so**
First PR out of a series. This one should enforce pre-KYC limits for the number of claimed triplers.

Caveats:

- Arithmetic assumes that only disbursable events are tripler claims, resulting in $30 each.
- With the default tripler limit set to 12, and the KYC threshold being at $500, the KYC limit of floor($500/$30)=16 will never be reached.
- There doesn't appear to be a place to place unit tests?

### CODE REVIEW

**Comment by shauminn-colab** [comment]
@arik-so - each payout is $25 rather than $30. Default tripler limit is set to 20, but admins can increase the limit to allow for more earning for specific ambassadors: 
https://github.com/colab-coop/HelloVoter-admin-ui/pull/35

**Comment by arik-so** [comment]
I see. Here, the payout value is read from the config/.env. With the key it's accessing, will it be correct?

**Comment by shauminn-colab** [comment]
yes it should still be correctly set based on the .env variable `PAYOUT_PER_TRIPLER`

**Comment by arik-so** [comment]
I rebased to resolve conflicts, and it seems to have decided a bunch of old commits are now new. Let me know if you'd like me to reöpen this PR.

**Comment by shauminn-colab** [comment]
argh, that's so weird, sorry about that. is it difficult to reopen the PR with just your changes or pretty easy?

**Comment by arik-so** [comment]
It should be fairly easy. I'll cherry pick onto a new branch.

**Pull request closed without merging**
